### ISSUE TITLE
doesn't work with jQuery 3.1.1?

### ISSUE THREAD

**Issue by Exodus000** [vanderlee/coverflow#36]
if change the script to the up-to-date version it won't work, any method or function needed to be modfied to make it works?

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.js"></script>

**Comment by vanderlee** [comment]
Confirmed.
It seems to work mostly, but the CSS is not handled correctly starting with jQuery 3.0.0.
I'll see if I can find a quick fix.

**Comment by vanderlee** [comment]
Apparently, jQuery 3 calculates `.outerWidth()` differently. Pre-3, it returns the width as-if not transformed in CSS, post-3, the transform is taken into account, returning unexpected values. The problem is this one here: https://github.com/jquery/jquery/issues/3193. jQuery made a backwards incompatible change and, at the moment, seems unlikely to revert it.

**Comment by vanderlee** [comment]
I have a fix. It's a bit ugly, but it should work fine in all jQuery version. I've tested with jQuery 2 and 3.
Could you please verify?

**Comment by Exodus000** [comment]
Still doesn't work if I added jQuery 3.1.1 using google CDN, works fine with 2.x
